export const environment = {
  production: true,
  envName: 'prod',
  assignmentProjectJira: 'REM',
  gitHash: 'GIT_HASH_PLACEHOLDER',
  apiUrl: 'https://remoteu.trilogy.com/api',
  itSystemAccessGetUrl: 'https://5lwj6352lh.execute-api.us-east-1.amazonaws.com/prod/report-issue-it-systems-access-get',
  preStartConfirmAccessesGetUrl: 'https://5lwj6352lh.execute-api.us-east-1.amazonaws.com/prod/confirm-accesses-get',
  preStartConfirmAccessesPutUrl: 'https://5lwj6352lh.execute-api.us-east-1.amazonaws.com/prod/confirm-accesses-put',
  remoteUMaterialsReportIssueGetUrl: 'https://5lwj6352lh.execute-api.us-east-1.amazonaws.com/prod/report-issue-remote-u-materials-get',
  codeRepositoryIssueGetUrl: 'https://5lwj6352lh.execute-api.us-east-1.amazonaws.com/prod/reporting_issue_code_repo_get',
  reportIssuePostUrl: 'https://5lwj6352lh.execute-api.us-east-1.amazonaws.com/prod/reporting_issue_post',
  checkAssignmentFolderGetUrl: 'https://94zqaokrwc.execute-api.us-east-1.amazonaws.com/prod/check-drive',
  readyToStartGetUrl: 'https://5lwj6352lh.execute-api.us-east-1.amazonaws.com/prod/ready-to-start-get',
  jiraStatusGetUrl: 'https://np109yeyje.execute-api.us-east-1.amazonaws.com/prod/jira-check',
  ticketsAssignedGetUrl: 'https://gezqhdy74j.execute-api.us-east-1.amazonaws.com/prod/backlog_status',
  remoteUCodeRepoAccess: 'https://5lwj6352lh.execute-api.us-east-1.amazonaws.com/prod/check-remotecamp-public-access',
  workSmartTrainingsUrl: 'https://xxhj8mghhl.execute-api.us-east-1.amazonaws.com/prod/ws-pro',
  technicalTrainingsUrl: 'https://xxhj8mghhl.execute-api.us-east-1.amazonaws.com/prod/technical',
  communicationChannelAccessUrl: 'https://5lwj6352lh.execute-api.us-east-1.amazonaws.com/prod/check-xoChat-registeration-get',
  knowledgeBaseUrl: 'https://zxzfv9hcm0.execute-api.us-east-1.amazonaws.com/prod/refresh-kb',
  knowledgeBaseStatusUrl: 'https://zxzfv9hcm0.execute-api.us-east-1.amazonaws.com/prod/status'
};
