export const environment = {
  production: false,
  envName: 'reg',
  assignmentProjectJira: 'TREM',
  gitHash: 'GIT_HASH_PLACEHOLDER',
  apiUrl: 'https://dev-remoteu.trilogy.com/api',
  itSystemAccessGetUrl: 'https://hmart2ms7g.execute-api.us-east-1.amazonaws.com/dev/report-issue-it-systems-access-get',
  preStartConfirmAccessesGetUrl: 'https://hmart2ms7g.execute-api.us-east-1.amazonaws.com/dev/confirm-accesses-get',
  preStartConfirmAccessesPutUrl: 'https://hmart2ms7g.execute-api.us-east-1.amazonaws.com/dev/confirm-accesses-put',
  remoteUMaterialsReportIssueGetUrl: 'https://hmart2ms7g.execute-api.us-east-1.amazonaws.com/dev/report-issue-remote-u-materials-get',
  codeRepositoryIssueGetUrl: 'https://hmart2ms7g.execute-api.us-east-1.amazonaws.com/dev/reporting_issue_code_repo_get',
  reportIssuePostUrl: 'https://hmart2ms7g.execute-api.us-east-1.amazonaws.com/dev/reporting_issue_post',
  checkAssignmentFolderGetUrl: 'https://1w7y8f0ox9.execute-api.us-east-1.amazonaws.com/dev/check-drive',
  readyToStartGetUrl: 'https://hmart2ms7g.execute-api.us-east-1.amazonaws.com/dev/ready-to-start-get',
  jiraStatusGetUrl: 'https://a185kccj8c.execute-api.us-east-1.amazonaws.com/dev/jira-check',
  ticketsAssignedGetUrl: 'https://cj84gm0eh7.execute-api.us-east-1.amazonaws.com/dev/backlog_status',
  remoteUCodeRepoAccess: 'https://hmart2ms7g.execute-api.us-east-1.amazonaws.com/dev/check-remotecamp-public-access',
  workSmartTrainingsUrl: 'https://svgyepe0pf.execute-api.us-east-1.amazonaws.com/reg/ws-pro',
  technicalTrainingsUrl: 'https://svgyepe0pf.execute-api.us-east-1.amazonaws.com/reg/technical',
  communicationChannelAccessUrl: 'https://hmart2ms7g.execute-api.us-east-1.amazonaws.com/reg/check-xoChat-registeration-get',
  knowledgeBaseUrl: 'https://m94tm6iebk.execute-api.us-east-1.amazonaws.com/reg/refresh-kb',
  knowledgeBaseStatusUrl: 'https://m94tm6iebk.execute-api.us-east-1.amazonaws.com/reg/status'
};
